services:
  db:
    image: postgres:16-alpine
    container_name: shawarmys-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shawarmys
      POSTGRES_USER: shawarmys
      POSTGRES_PASSWORD: shawarmys
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
