services:
  db:
    image: postgres:16-alpine
    container_name: shawarmys-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: shawarmys
      POSTGRES_USER: shawarmys
      POSTGRES_PASSWORD: shawarmys
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: shawarmys-server
    depends_on:
      - db
    ports:
      - "8000:80"
    expose:
      - "80"
    environment:
      DATABASE_URL: postgresql://shawarmys:shawarmys@db:5432/shawarmys

  client:
    build:
      context: ./client
    container_name: shawarmys-client
    depends_on:
      - server
    ports:
      - "90:90"

volumes:
  postgres_data:
